apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: join-on-map
spec:
  vertices:
    - name: http-in
      source:
        http: {}
    - name: kafka-in
      source:
        kafka:
          brokers:
            - host.minikube.internal:29092
          topic: coba
          consumerGroup: console-consumer-78922
    # Both of the incoming Vertices join on this Map Vertex
    - name: cat
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: out
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: http-in
      to: cat
    - from: kafka-in
      to: cat
    - from: cat
      to: out
